(function(){
"use strict";
var cfg=GameUI.CustomUIConfig(),U=cfg.SurvivalUI,RH=cfg.RemainingHandoff,data=null,waiting=null,errorText='',buying=false,sequence=0,active=true,life=U.Lifecycle(),viewLife=U.Lifecycle(),fetching=false,fetchSerial=0,shell;
var premiumCard=null,purpleShell=null,dailyTooltipSource=null,dailyHideJob=null,dailyTipSerial=0;
var dailyRoot=$.GetContextPanel();if(!viewValid()){active=false;return;}
if(cfg.SurvivalDaily&&cfg.SurvivalDaily.Dispose)cfg.SurvivalDaily.Dispose();
function valid(panel){return panel&&(!panel.IsValid||panel.IsValid());}function p(id){return valid(dailyRoot)?dailyRoot.FindChildTraverse(id):null;}function viewValid(){return valid(p('DailyWindow'));}function stopIfInvalid(){if(!active)return true;if(viewValid())return false;active=false;life.Dispose();if(typeof viewLife!=='undefined')viewLife.Dispose();if(shell)shell.Dispose();return true;}function array(v){return Array.isArray(v)?v:Object.keys(v||{}).sort(function(a,b){return Number(a)-Number(b);}).map(function(k){return v[k];});}
function label(parent,text,cls){var l=$.CreatePanel('Label',parent,'');l.text=String(text||'');l.hittest=false;l.AddClass(cls||'DailyText');return l;}
function escapedLines(value){return String(value||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\r?\n/g,'<br>');}
function rect(p,x,y,w,h){p.style.position=x+'px '+y+'px 0px';p.style.width=w+'px';p.style.height=h+'px';}
function image(parent,id,cls){return RH.DailyImage(parent,id,cls);}
function cancelTooltipHide(){dailyTipSerial++;if(dailyHideJob!==null&&$.CancelScheduled)$.CancelScheduled(dailyHideJob);dailyHideJob=null;}
function hideTooltip(){cancelTooltipHide();dailyTooltipSource=null;if(valid(p('DailyTooltip'))){p('DailyTooltip').AddClass('ArchiveHidden');p('DailyTooltip').hittest=false;p('DailyTooltip').hittestchildren=false;}}
function canShowTooltip(){var rules=p('DailyRulesText');return active&&viewValid()&&shell&&shell.IsOpen()&&(!valid(rules)||rules.BHasClass('ArchiveHidden'));}
function leaveTooltip(){cancelTooltipHide();var serial=dailyTipSerial;dailyHideJob=$.Schedule(.18,function(){dailyHideJob=null;if(serial===dailyTipSerial)hideTooltip();});}
function placeTooltip(source){var tooltip=p('DailyTooltip'),windowPanel=p('DailyWindow');if(!valid(source)||!valid(tooltip)||!valid(windowPanel)||dailyTooltipSource!==source||!source.GetPositionWithinWindow)return;var origin=windowPanel.GetPositionWithinWindow(),anchor=source.GetPositionWithinWindow(),scale=Math.max(.001,Number(windowPanel.actualuiscale_x)||1),x=(anchor.x-origin.x)/scale,y=(anchor.y-origin.y)/scale,w=(Number(windowPanel.actuallayoutwidth)||1280)/scale,h=(Number(windowPanel.actuallayoutheight)||800)/scale,sw=(Number(source.actuallayoutwidth)||128)/scale,sh=(Number(source.actuallayoutheight)||152)/scale,tw=(Number(tooltip.actuallayoutwidth)||330)/scale,th=(Number(tooltip.actuallayoutheight)||240)/scale,left=x+sw+12;if(left+tw>w-14)left=x-tw-12;left=Math.max(14,Math.min(left,w-tw-14));var top=Math.max(140,Math.min(y+(sh-th)/2,h-th-18));tooltip.style.position=Math.round(left)+'px '+Math.round(top)+'px 0px';}
function tip(anchor,title,body){anchor.hittest=true;anchor.SetPanelEvent('onmouseover',function(){if(!canShowTooltip()){hideTooltip();return;}cancelTooltipHide();dailyTooltipSource=anchor;p('DailyTooltipName').text=title;p('DailyTooltipEffect').text=body||'属性待接入';var tooltip=p('DailyTooltip');tooltip.RemoveClass('ArchiveHidden');tooltip.hittest=true;tooltip.hittestchildren=true;placeTooltip(anchor);$.Schedule(.03,function(){placeTooltip(anchor);});});anchor.SetPanelEvent('onmouseout',leaveTooltip);}
function iconButton(p,name,action){p.AddClass('DailyIcon_'+name);var a=$.CreatePanel('Panel',p,'');a.AddClass('DailyIconArt');a.hittest=false;p.hittestchildren=false;U.State.Bind(p,action);}
function close(){if(!active)return;hideTooltip();viewLife.Cancel();fetching=false;fetchSerial++;shell.Close();if(valid(p('DailyWindow')))p('DailyWindow').AddClass('ArchiveHidden');if(valid(p('DailyScrim')))p('DailyScrim').AddClass('ArchiveHidden');if(valid(p('DailyRulesText')))p('DailyRulesText').AddClass('ArchiveHidden');$.DispatchEvent('DOTAHideTextTooltip');}
shell=U.ModalShell.Adopt({id:'daily_rewards',panel:p('DailyWindow'),root:$.GetContextPanel(),scrim:p('DailyScrim'),width:1280,height:800,fit:{reference:[1920,1080]},onClose:close});
p('DailyWindow').style.backgroundColor='transparent';p('DailyWindow').style.border='0px';p('DailyWindow').style.boxShadow='none';p('DailyScrim').style.backgroundColor='#00000033';
RH.Window(p('DailyWindow'),p('DailyHeader'),p('DailyClose'));RH.SizeWindow(p('DailyWindow'),1280,800);
var dailyWindow=p('DailyWindow');dailyWindow.AddClass('DailyPurple');if(cfg.SurvivalPurpleShell)purpleShell=cfg.SurvivalPurpleShell.Adopt({id:'daily_rewards',panel:dailyWindow,width:1280,height:800,onClose:close});
// ReferenceWindows applies inline legacy colors and sizes before this controller's theme.
var rulesPopup=p('DailyRulesText'),rulesBody=p('DailyRulesBody');rect(rulesPopup,184,164,912,516);rulesPopup.style.height='fit-children';rulesPopup.style.maxHeight='516px';rulesPopup.style.backgroundImage='none';rulesPopup.style.backgroundColor='gradient(linear,0% 0%,100% 100%,from(#211630),to(#0e0b1b))';rulesPopup.style.border='1px solid #b18a50';rulesPopup.style.padding='28px';rulesPopup.style.flowChildren='down';rulesPopup.style.overflow='squish scroll';rulesPopup.style.zIndex='150';rulesBody.html=true;rulesBody.style.width='840px';rulesBody.style.maxWidth='840px';rulesBody.style.height='fit-children';rulesBody.style.margin='0px';rulesBody.style.whiteSpace='normal';rulesBody.style.textOverflow='clip';rulesBody.style.fontSize='19px';rulesBody.style.fontWeight='normal';rulesBody.style.lineHeight='28px';rulesBody.style.color='#e0cfee';
p('DailyScrim').style.backgroundColor='#07040eb8';
U.Tooltip.Adopt(p('DailyTooltip'));p('DailyTooltip').SetPanelEvent('onmouseover',function(){if(!canShowTooltip())hideTooltip();else cancelTooltipHide();});p('DailyTooltip').SetPanelEvent('onmouseout',leaveTooltip);
var dailyEmblem=$.CreatePanel('Image',p('DailyHeader'),'DailyReferenceEmblem');dailyEmblem.hittest=false;dailyEmblem.SetImage('file://{images}/custom_game/topnav_reference_v2/benefit_clean.svg');rect(dailyEmblem,32,20,48,48);
p('DailyClose').SetPanelEvent('onactivate',shell.RequestClose);
iconButton(p('DailyRules'),'rules_local',function(){hideTooltip();p('DailyRulesText').ToggleClass('ArchiveHidden');});
iconButton(p('DailyPassStatus'),'pass',function(){hideTooltip();buying=true;render();});
U.ActionButton.Adopt(p('DailyClaim'),{action:function(){if(!data){request();return;}claim(data.today);}});p('DailyClaim').AddClass('DailyClaimSkin');
U.ActionButton.Adopt(p('DailyMakeup'),{action:function(){claim(array(data&&data.missed)[0]);}});
U.ActionButton.Adopt(p('PassPurchase'),{action:function(){if(!data||Number(data.purchase_enabled)!==1)return;U.State.Set(p('PassPurchase'),{enabled:false});GameEvents.SendCustomGameEventToServer('survival_pass_purchase',{});}});
U.ActionButton.Adopt(p('DailyBack'),{action:function(){hideTooltip();buying=false;render();}});
RH.Action(p('DailyClaim'),true);p('DailyMakeup').visible=false;
var spinner=image(p('DailyClaim'),'daily.icon.spinner','DailySpinner');
function request(){if(stopIfInvalid())return;if(!active||fetching)return;fetching=true;var serial=++fetchSerial;if(!data){errorText='';render();}GameEvents.SendCustomGameEventToServer('survival_daily_request',{});if(shell.IsOpen())viewLife.Later(8,function(){if(!active||serial!==fetchSerial||!fetching)return;fetching=false;if(!data){errorText='读取奖励超时，请重试';render();}});else fetching=false;}
function emptyView(){if(!shell.IsOpen())return;p('DailyHeading').text='每日奖励';p('DailyClaimPage').RemoveClass('ArchiveHidden');p('DailyPassPage').AddClass('ArchiveHidden');p('DailySubtitle').text='';p('DailyCount').text='';p('DailyPassStatusText').text='';p('DailyRuleLine').text='';p('DailyCards').RemoveAndDeleteChildren();if(valid(premiumCard))premiumCard.visible=false;hideTooltip();p('DailyMakeup').visible=false;p('DailyNotice').text=errorText||'正在读取每日奖励…';p('DailyClaimText').text=fetching?'加载中…':'重试加载';spinner.visible=fetching;U.State.Set(p('DailyClaim'),{enabled:!fetching,busy:fetching});U.State.Set(p('DailyMakeup'),{enabled:false});U.State.Set(p('DailyPassStatus'),{enabled:false});paintActions();}
// Existing stat gems/fragments use crystal category art; names/counts/effects remain authoritative.
function artId(item){return item.art_id&&RH.DailyResourceInfo(item.art_id).runtime?item.art_id:'daily.item.crystals';}
function reward(parent,item,cls){var slot=$.CreatePanel('Panel',parent,'');slot.AddClass(cls);((cfg.SurvivalItemArt&&cfg.SurvivalItemArt.Create(slot,item,'DailyItemArt'))||image(slot,artId(item),'DailyItemArt')).SetScaling('stretch-to-fit-preserve-aspect');var count=Number(item.count),known=item.count!==undefined&&item.count!==null&&isFinite(count)&&count>=0,quantity=label(slot,known?'×'+count:'','DailyRewardQuantity');quantity.visible=known;label(slot,item.name,'DailyRewardName');tip(slot,item.name,(item.description||'属性待接入')+(known?'\n数量：'+count:''));return slot;}
function stateIcon(parent,s){return image(parent,s==='claimed'?'daily.icon.claimed':s==='requires_pass'||s==='unconfigured'?'daily.icon.lock':'daily.icon.clock','DailyStateIcon');}
function stateText(s){return {claimed:'已领取',claimable:'今日可领',not_open:'尚未开放',requires_pass:'通行证专属',unconfigured:'暂未开放'}[s]||'待接入';}
var cardSignature='';
function renderCards(){var next=JSON.stringify([data.cycle,data.premium]);if(next===cardSignature&&p('DailyCards').GetChildCount()===7)return;cardSignature=next;hideTooltip();p('DailyCards').RemoveAndDeleteChildren();array(data.cycle).slice(0,7).forEach(function(day,i){
var last=i===6,card=$.CreatePanel('Panel',p('DailyCards'),'');card.AddClass(last?'DailyWeekCard':'DailyNormalCard');rect(card,28+(i%4)*308,200+Math.floor(i/4)*238,286,224);
var s=day.status||'not_open',today=Number(day.is_today)===1;RH.DailyCard(card,last,today);card.SetHasClass('DailyToday',today);card.SetHasClass('DailyFuture',s==='not_open');label(card,'第'+day.day+'天','DailyDay');label(card,stateText(s),'DailyCardStatus');
var rewards=array(day.rewards),items=$.CreatePanel('Panel',card,'');items.AddClass('DailyItems');items.SetHasClass('DailyMultiItem',rewards.length>1);rewards.forEach(function(item,j){var slot=reward(items,item,'DailyReward');rect(slot,rewards.length>1?5+j*138:74,0,138,168);});
});
if(!valid(premiumCard)){premiumCard=$.CreatePanel('Panel',p('DailyClaimPage'),'DailyPurplePremium');premiumCard.AddClass('DailyPremiumCard');}premiumCard.visible=true;premiumCard.RemoveAndDeleteChildren();rect(premiumCard,952,438,286,224);label(premiumCard,'通行证专属','DailyDay');var premium=data.premium||{status:'unconfigured',name:'周末高级装备'};label(premiumCard,stateText(premium.status),'DailyCardStatus');var extra=$.CreatePanel('Panel',premiumCard,'');extra.AddClass('DailyPremiumReward');extra.SetHasClass('Unconfigured',premium.status==='unconfigured');if(premium.status==='unconfigured')image(extra,'daily.icon.lock','DailyPremiumArt');else image(extra,premium.art_id||'daily.item.weapon','DailyPremiumArt').SetScaling('stretch-to-fit-preserve-aspect');label(extra,premium.name||'高级装备','DailyPremiumName');tip(extra,premium.name||'通行证奖励',premium.description||'该奖励暂未开放，请以开放后的说明为准。');}
function availability(){var base=data&&data.ordinary_status==='claimable',bonus=data&&data.premium&&data.premium.status==='claimable';return {enabled:!!(base||bonus),text:base?'领取今日奖励':bonus?'领取通行证奖励':data&&data.ordinary_status==='claimed'?'今日已领取':'尚未开放'};}
var specialSignature='';
function renderSpecials(){var rows=array(data.specials),signature=JSON.stringify(rows);if(signature===specialSignature&&p('DailySpecials').GetChildCount()===rows.length)return;specialSignature=signature;hideTooltip();p('DailySpecials').RemoveAndDeleteChildren();rows.forEach(function(item,i){var card=$.CreatePanel('Panel',p('DailySpecials'),'');card.AddClass('DailySpecial');rect(card,Math.max(0,(1210-(Math.min(4,rows.length)*308-22))/2)+(i%4)*308,Math.floor(i/4)*238,286,224);label(card,'累计'+item.day+'次','DailyMilestone');label(card,Number(item.owned)>0?'已领取':'未领取','DailySpecialState');var slot=reward(card,{id:item.id,name:item.name,description:item.description,count:1},'DailyReward');rect(slot,74,42,138,168);});}
function paintActions(){['DailyClaim','DailyMakeup','PassPurchase','DailyBack','DailyRules','DailyPassStatus'].forEach(function(id){var button=p(id);if(!valid(button))return;var primary=id==='DailyClaim'||id==='PassPurchase',disabled=button.enabled===false;button.style.backgroundImage='none';button.style.backgroundColor=disabled?'#21172f':primary?'gradient(linear,0% 0%,0% 100%,from(#734a9e),to(#382346))':'#281b3e';button.style.border='1px solid '+(disabled?'#594363':'#b18a50');button.hittestchildren=false;function paint(node){if(node.paneltype==='Label')node.style.color=disabled?'#a795b8':primary?'#ffdc87':'#d7c2ec';if(node.Children)node.Children().forEach(paint);}if(button.Children)button.Children().forEach(paint);});}
function render(){if(stopIfInvalid())return;RH=cfg.RemainingHandoff;if(!data){emptyView();return;}U.State.Set(p('DailyPassStatus'),{enabled:true});var ready=availability(),busy=!!waiting||Number(data.pending)===1;p('DailyEntry').SetHasClass('DailyCanClaim',ready.enabled);p('DailyEntry').SetHasClass('DailyClaimed',!ready.enabled&&data.ordinary_status==='claimed');if(!shell.IsOpen())return;
p('DailyHeading').text=buying?'星月通行证':'每日奖励';p('DailyClaimPage').SetHasClass('ArchiveHidden',buying);p('DailyPassPage').SetHasClass('ArchiveHidden',!buying);p('DailySubtitle').text=data.subtitle||'每日领取';p('DailyCount').text=data.cycle_mode==='claim_count'?'累计签到 '+data.count+' 次':'本周已领取 '+data.count+'/7 天';p('DailyPassStatusText').text=Number(data.has_pass)===1?'通行证已生效':'通行证未生效';RH.DailyPass(p('DailyPassStatus'),Number(data.has_pass)===1);p('DailyRuleLine').text=data.rule_text||'奖励以服务端配置为准';p('DailyRulesBody').text=escapedLines((data.rule_text||'')+'\n补签范围：最近'+(data.makeup_days||30)+'天，需有效通行证。\n'+array(data.specials).map(function(s){return '累计'+s.day+'次：'+s.name+'；'+s.description;}).join('\n'));
p('DailyClaimText').text=busy?'领取中…':errorText&&ready.enabled?'重试领取':ready.text;U.State.Set(p('DailyClaim'),{enabled:ready.enabled&&!busy,busy:busy});spinner.visible=busy;U.State.Set(p('DailyMakeup'),{enabled:Number(data.has_pass)===1&&array(data.missed).length>0&&!busy});p('DailyMakeup').visible=Number(data.has_pass)===1&&array(data.missed).length>0;p('DailyNotice').text=errorText||(busy?'正在等待服务端保存，请勿重复提交。':'');p('PassValidity').text=Number(data.has_pass)===1?'通行证有效':'通行证未开通或已到期';p('PassPrice').text=data.duration_days+'天 / '+data.price;p('PassPurchaseText').text=Number(data.purchase_enabled)===1?'购买 / 续费通行证':'购买暂未开放';U.State.Set(p('PassPurchase'),{enabled:Number(data.purchase_enabled)===1&&!busy});renderSpecials();renderCards();paintActions();}
function claim(target){if(!data||waiting||Number(data.pending)===1||target===undefined)return;waiting={target:Number(target),day:Number(data.today),period:String(data.period_id),count:Number(data.count)};errorText='';render();GameEvents.SendCustomGameEventToServer('survival_daily_claim',{target_day:Number(target)});}
life.Subscribe('survival_daily_snapshot',function(next){if(!active)return;fetching=false;fetchSerial++;if(!(next.ok===true||Number(next.ok)===1)){errorText=next.error||'正在读取档案';render();return;}if(Number(next.sequence)>0&&Number(next.sequence)<=sequence)return;if(data&&Number(next.today)<Number(data.today))return;sequence=Number(next.sequence)||sequence;var result=next.claim_result;if(waiting){if(Number(next.today)!==waiting.day||String(next.period_id)!==waiting.period){waiting=null;errorText='';}else if(Number(next.count)>waiting.count||(waiting.target===Number(next.today)&&next.ordinary_status==='claimed')){waiting=null;errorText='';}else if(result&&Number(result.target_day)===waiting.target&&Number(next.pending)!==1&&!result.pending){waiting=null;errorText=result.ok?'':result.error||'领取失败，请重试';}}data=next;if(!waiting&&!(result&&!result.ok))errorText='';render();});
function poll(){if(stopIfInvalid()||!active||!shell.IsOpen())return;request();viewLife.Later(3,poll);}
cfg.SurvivalDaily={Open:function(pass){if(!active||!viewValid())return;hideTooltip();buying=pass===true;p('DailyWindow').RemoveClass('ArchiveHidden');p('DailyScrim').RemoveClass('ArchiveHidden');shell.Open();viewLife.Cancel();fetching=false;render();request();viewLife.Later(3,poll);},Close:close,Inspect:function(){var cards=p('DailyCards');return {open:shell.IsOpen(),pass:buying,waiting:!!waiting,fetching:fetching,today:data&&data.today,count:data&&data.count,days:valid(cards)?cards.GetChildCount():0};},Dispose:function(){hideTooltip();active=false;viewLife.Dispose();life.Dispose();if(purpleShell)purpleShell.Dispose();shell.Dispose();}};life.Later(1,request);
})();
