(function(){
"use strict";
var cfg=GameUI.CustomUIConfig(),U=cfg.SurvivalUI,RH=cfg.RemainingHandoff,data=null,waiting=null,errorText='',buying=false,sequence=0,active=true,life=U.Lifecycle(),viewLife=U.Lifecycle(),fetching=false,fetchSerial=0,shell;
var dailyRoot=$.GetContextPanel();if(!viewValid()){active=false;return;}
if(cfg.SurvivalDaily&&cfg.SurvivalDaily.Dispose)cfg.SurvivalDaily.Dispose();
function valid(panel){return panel&&(!panel.IsValid||panel.IsValid());}function p(id){return valid(dailyRoot)?dailyRoot.FindChildTraverse(id):null;}function viewValid(){return valid(p('DailyWindow'));}function stopIfInvalid(){if(!active)return true;if(viewValid())return false;active=false;life.Dispose();if(typeof viewLife!=='undefined')viewLife.Dispose();if(shell)shell.Dispose();return true;}function array(v){return Array.isArray(v)?v:Object.keys(v||{}).sort(function(a,b){return Number(a)-Number(b);}).map(function(k){return v[k];});}
function label(parent,text,cls){var l=$.CreatePanel('Label',parent,'');l.text=String(text||'');l.hittest=false;l.AddClass(cls||'DailyText');return l;}
function rect(p,x,y,w,h){p.style.position=x+'px '+y+'px 0px';p.style.width=w+'px';p.style.height=h+'px';}
function image(parent,id,cls){return RH.DailyImage(parent,id,cls);}function tip(p,title,body){RH.DailyTooltip(p,title,body);}
function iconButton(p,name,action){p.AddClass('DailyIcon_'+name);var a=$.CreatePanel('Panel',p,'');a.AddClass('DailyIconArt');a.hittest=false;p.hittestchildren=false;U.State.Bind(p,action);}
function close(){if(!active)return;viewLife.Cancel();fetching=false;fetchSerial++;shell.Close();if(valid(p('DailyWindow')))p('DailyWindow').AddClass('ArchiveHidden');if(valid(p('DailyScrim')))p('DailyScrim').AddClass('ArchiveHidden');if(valid(p('DailyRulesText')))p('DailyRulesText').AddClass('ArchiveHidden');if(valid(p('DailyTooltip')))p('DailyTooltip').AddClass('ArchiveHidden');$.DispatchEvent('DOTAHideTextTooltip');}
shell=U.ModalShell.Adopt({id:'daily_rewards',panel:p('DailyWindow'),root:$.GetContextPanel(),scrim:p('DailyScrim'),width:1344,height:752,fit:{reference:[1672,941]},onClose:close});
p('DailyWindow').style.backgroundColor='transparent';p('DailyWindow').style.border='0px';p('DailyWindow').style.boxShadow='none';p('DailyScrim').style.backgroundColor='#0000008c';
RH.Window(p('DailyWindow'),p('DailyHeader'),p('DailyClose'));RH.SizeWindow(p('DailyWindow'),1344,752);
rect(image(p('DailyHeader'),'daily.icon.calendar.normal','DailyCalendar'),547,24,38,38);
p('DailyClose').SetPanelEvent('onactivate',shell.RequestClose);
iconButton(p('DailyRules'),'rules_local',function(){p('DailyRulesText').ToggleClass('ArchiveHidden');});
iconButton(p('DailyPassStatus'),'pass',function(){buying=true;render();});
U.ActionButton.Adopt(p('DailyClaim'),{action:function(){if(!data){request();return;}claim(data.today);}});p('DailyClaim').AddClass('DailyClaimSkin');
U.ActionButton.Adopt(p('DailyMakeup'),{action:function(){claim(array(data&&data.missed)[0]);}});
U.ActionButton.Adopt(p('PassPurchase'),{action:function(){if(!data||Number(data.purchase_enabled)!==1)return;U.State.Set(p('PassPurchase'),{enabled:false});GameEvents.SendCustomGameEventToServer('survival_pass_purchase',{});}});
U.ActionButton.Adopt(p('DailyBack'),{action:function(){buying=false;render();}});
RH.Action(p('DailyClaim'));p('DailyMakeup').visible=false;
var spinner=image(p('DailyClaim'),'daily.icon.spinner','DailySpinner');
function request(){if(stopIfInvalid())return;if(!active||fetching)return;fetching=true;var serial=++fetchSerial;if(!data){errorText='';render();}GameEvents.SendCustomGameEventToServer('survival_daily_request',{});if(shell.IsOpen())viewLife.Later(8,function(){if(!active||serial!==fetchSerial||!fetching)return;fetching=false;if(!data){errorText='读取奖励超时，请重试';render();}});else fetching=false;}
function emptyView(){if(!shell.IsOpen())return;p('DailyHeading').text='每日奖励';p('DailyClaimPage').RemoveClass('ArchiveHidden');p('DailyPassPage').AddClass('ArchiveHidden');p('DailySubtitle').text='';p('DailyCount').text='';p('DailyPassStatusText').text='';p('DailyRuleLine').text='';p('DailyCards').RemoveAndDeleteChildren();p('DailyNotice').text=errorText||'正在读取每日奖励…';p('DailyClaimText').text=fetching?'加载中…':'重试加载';spinner.visible=fetching;U.State.Set(p('DailyClaim'),{enabled:!fetching,busy:fetching});U.State.Set(p('DailyMakeup'),{enabled:false});U.State.Set(p('DailyPassStatus'),{enabled:false});}
// Existing stat gems/fragments use crystal category art; names/counts/effects remain authoritative.
function artId(item){return item.art_id&&RH.DailyResourceInfo(item.art_id).runtime?item.art_id:'daily.item.crystals';}
function reward(parent,item,cls){var slot=$.CreatePanel('Panel',parent,'');slot.AddClass(cls);((cfg.SurvivalItemArt&&cfg.SurvivalItemArt.Create(slot,item,'DailyItemArt'))||image(slot,artId(item),'DailyItemArt')).SetScaling('stretch-to-fit-preserve-aspect');label(slot,item.name+' ×'+item.count,'DailyRewardName');tip(slot,item.name,item.description||'属性待接入');return slot;}
function stateIcon(parent,s){return image(parent,s==='claimed'?'daily.icon.claimed':s==='requires_pass'||s==='unconfigured'?'daily.icon.lock':'daily.icon.clock','DailyStateIcon');}
function stateText(s){return {claimed:'已领取',claimable:'今日可领',not_open:'尚未开放',requires_pass:'通行证专属',unconfigured:'待配置'}[s]||'待接入';}
var cardSignature='';
function renderCards(){var next=JSON.stringify([data.cycle,data.premium]);if(next===cardSignature&&p('DailyCards').GetChildCount()===7)return;cardSignature=next;p('DailyCards').RemoveAndDeleteChildren();array(data.cycle).slice(0,7).forEach(function(day,i){
var last=i===6,card=$.CreatePanel('Panel',p('DailyCards'),'');card.RemoveClass('UICardSquare');card.AddClass(last?'DailyWeekCard':'DailyNormalCard');rect(card,last?1000:40+i*159,192,last?310:153,390);
var s=day.status||'not_open',today=Number(day.is_today)===1;RH.DailyCard(card,last,today);card.SetHasClass('DailyToday',today);card.SetHasClass('DailyFuture',s==='not_open');label(card,'第'+day.day+'天','DailyDay');
var rewards=array(day.rewards);
if(!last){var items=$.CreatePanel('Panel',card,'');items.AddClass('DailyItems');items.SetHasClass('DailyMultiItem',rewards.length>1);rewards.forEach(function(item){reward(items,item,'DailyReward');});stateIcon(card,s);label(card,stateText(s),'DailyCardStatus');}
else{var base=$.CreatePanel('Panel',card,'');base.AddClass('DailyBaseReward');rewards.forEach(function(item){reward(base,item,'DailyReward');});label(base,stateText(s),'DailyBaseStatus');var premium=data.premium||{status:'unconfigured',name:'周末高级装备'},extra=$.CreatePanel('Panel',card,'');extra.AddClass('DailyPremiumReward');image(extra,'daily.badge.premium','DailyPremiumBadge');label(extra,'通行证专属','DailyPremiumTag');if(premium.status!=='unconfigured')image(extra,premium.art_id||'daily.item.weapon','DailyPremiumArt').SetScaling('stretch-to-fit-preserve-aspect');label(extra,premium.name||'高级装备','DailyPremiumName');stateIcon(extra,premium.status);label(extra,stateText(premium.status),'DailyPremiumState');tip(extra,premium.name||'通行证奖励',premium.description||'奖励配置待接入');}
});}
function availability(){var base=data&&data.ordinary_status==='claimable',bonus=data&&data.premium&&data.premium.status==='claimable';return {enabled:!!(base||bonus),text:base?'领取今日奖励':bonus?'领取通行证奖励':data&&data.ordinary_status==='claimed'?'今日已领取':'尚未开放'};}
function render(){if(stopIfInvalid())return;if(!data){emptyView();return;}U.State.Set(p('DailyPassStatus'),{enabled:true});var ready=availability(),busy=!!waiting||Number(data.pending)===1;p('DailyEntry').SetHasClass('DailyCanClaim',ready.enabled);p('DailyEntry').SetHasClass('DailyClaimed',!ready.enabled&&data.ordinary_status==='claimed');if(!shell.IsOpen())return;
p('DailyHeading').text=buying?'星月通行证':'每日奖励';p('DailyClaimPage').SetHasClass('ArchiveHidden',buying);p('DailyPassPage').SetHasClass('ArchiveHidden',!buying);p('DailySubtitle').text=data.subtitle||'每日领取';p('DailyCount').text=data.cycle_mode==='claim_count'?'累计签到 '+data.count+' 次':'本周已领取 '+data.count+'/7 天';p('DailyPassStatusText').text=Number(data.has_pass)===1?'通行证已生效':'通行证未生效';RH.DailyPass(p('DailyPassStatus'),Number(data.has_pass)===1);p('DailyRuleLine').text=data.rule_text||'奖励以服务端配置为准';p('DailyRulesBody').text=(data.rule_text||'')+'\n补签范围：最近'+(data.makeup_days||30)+'天，需有效通行证。\n'+array(data.specials).map(function(s){return '累计'+s.day+'次：'+s.name+'；'+s.description;}).join('\n');
p('DailyClaimText').text=busy?'领取中…':errorText&&ready.enabled?'重试领取':ready.text;U.State.Set(p('DailyClaim'),{enabled:ready.enabled&&!busy,busy:busy});spinner.visible=busy;U.State.Set(p('DailyMakeup'),{enabled:Number(data.has_pass)===1&&array(data.missed).length>0&&!busy});p('DailyNotice').text=errorText||(busy?'正在等待服务端保存，请勿重复提交。':'');p('PassValidity').text=Number(data.has_pass)===1?'通行证有效':'通行证未开通或已到期';p('PassPrice').text=data.duration_days+'天 / '+data.price;p('PassPurchaseText').text=Number(data.purchase_enabled)===1?'购买 / 续费通行证':'购买暂未开放';U.State.Set(p('PassPurchase'),{enabled:Number(data.purchase_enabled)===1&&!busy});p('DailySpecials').RemoveAndDeleteChildren();array(data.specials).forEach(function(item){var card=U.CardShell(p('DailySpecials'),{title:item.name});card.AddClass('DailySpecial');label(card,'累计'+item.day+'次 · '+(Number(item.owned)>0?'已领取':'未领取'));tip(card,item.name,item.description);});renderCards();}
function claim(target){if(!data||waiting||Number(data.pending)===1||target===undefined)return;waiting={target:Number(target),day:Number(data.today),period:String(data.period_id),count:Number(data.count)};errorText='';render();GameEvents.SendCustomGameEventToServer('survival_daily_claim',{target_day:Number(target)});}
life.Subscribe('survival_daily_snapshot',function(next){if(!active)return;fetching=false;fetchSerial++;if(!(next.ok===true||Number(next.ok)===1)){errorText=next.error||'正在读取档案';render();return;}if(Number(next.sequence)>0&&Number(next.sequence)<=sequence)return;if(data&&Number(next.today)<Number(data.today))return;sequence=Number(next.sequence)||sequence;var result=next.claim_result;if(waiting){if(Number(next.today)!==waiting.day||String(next.period_id)!==waiting.period){waiting=null;errorText='';}else if(Number(next.count)>waiting.count||(waiting.target===Number(next.today)&&next.ordinary_status==='claimed')){waiting=null;errorText='';}else if(result&&Number(result.target_day)===waiting.target&&Number(next.pending)!==1&&!result.pending){waiting=null;errorText=result.ok?'':result.error||'领取失败，请重试';}}data=next;if(!waiting&&!(result&&!result.ok))errorText='';render();});
function poll(){if(stopIfInvalid()||!active||!shell.IsOpen())return;request();viewLife.Later(3,poll);}
cfg.SurvivalDaily={Open:function(pass){if(!active||!viewValid())return;buying=pass===true;p('DailyWindow').RemoveClass('ArchiveHidden');p('DailyScrim').RemoveClass('ArchiveHidden');shell.Open();viewLife.Cancel();fetching=false;render();request();viewLife.Later(3,poll);},Close:close,Dispose:function(){active=false;viewLife.Dispose();life.Dispose();shell.Dispose();}};life.Later(1,request);
})();
