(function () {
    "use strict";
    var cfg=GameUI.CustomUIConfig(),registry=cfg.SurvivalUIRegistry;
    if(!registry)throw new Error("Shared UI registry must load before components");
    if(cfg.SurvivalUI&&cfg.SurvivalUI.version==="1.0.2")return;
    var U={version:"1.0.2",Tokens:registry.tokens},serial=0,modals={};
    function valid(p){return p&&(!p.IsValid||p.IsValid());}
    function apply(p,s){if(valid(p))Object.keys(s).forEach(function(k){p.style[k]=s[k];});}
    function create(type,parent,id,cls){var p=$.CreatePanel(type,parent,id||"");if(cls)p.AddClass(cls);return p;}
    function label(parent,text,cls){var p=create("Label",parent,"",cls);p.text=text===undefined?"":String(text);p.hittest=false;return p;}
    function clearClass(p,c,on){p.SetHasClass(c,!!on);}
    U.Asset=function(id){var a=registry.assets[id];if(!a)throw new Error("Unregistered UI resource: "+id);return "file://{images}/"+a.runtime;};
    U.ResourceInfo=function(id){return registry.assets[id]||{pending:registry.pending[id]};};
    U.LegacyId=function(path){var a=registry.aliases[path];if(!a)throw new Error("Unmapped legacy asset "+path);return a.target;};
    U.ProjectId=function(path){var id=registry.projectPaths[path];if(!id)throw new Error("Unregistered project variant "+path);return id;};
    U.ProjectAsset=function(path){return U.Asset(U.ProjectId(path));};
    U.Image=function(parent,id,cls){var p=create("Image",parent,"",cls);p.SetImage(U.Asset(id));p.hittest=false;return p;};
    U.Icon=function(parent,id,glyph,cls){var host=create("Panel",parent,"",cls||"UIIcon"),a=registry.assets[id];if(!a)throw new Error("Missing icon "+id);glyph=glyph||28;apply(host,{width:glyph+"px",height:glyph+"px",overflow:"noclip"});host.hittest=false;host.hittestchildren=false;
        var b=a.paint_bounds_xyxy||[0,0,a.size[0],a.size[1]],s=glyph/Math.max(b[2]-b[0],b[3]-b[1]),image=U.Image(host,id,"UIIconImage");apply(image,{width:a.size[0]*s+"px",height:a.size[1]*s+"px",position:((glyph-(b[2]-b[0])*s)/2-b[0]*s)+"px "+((glyph-(b[3]-b[1])*s)/2-b[1]*s)+"px 0px"});return host;};
    U.State={Set:function(p,props){props=props||{};if(props.enabled!==undefined){p.enabled=!!props.enabled;clearClass(p,"UIDisabled",!props.enabled);}if(props.busy!==undefined)clearClass(p,"UIBusy",props.busy);if(props.selected!==undefined)clearClass(p,"UISelected",props.selected);},CanActivate:function(p){return p.enabled!==false&&!p.BHasClass("UIDisabled")&&!p.BHasClass("UIBusy");},Bind:function(p,fn){p.SetPanelEvent("onactivate",function(){if(U.State.CanActivate(p)&&fn)fn(p);});}};
    U.Lifecycle=function(){var timers=[],subscriptions=[],generation=0;return {Later:function(delay,fn){var g=generation,id;id=$.Schedule(delay,function(){timers=timers.filter(function(t){return t!==id;});if(g===generation)fn();});timers.push(id);return id;},Subscribe:function(event,fn){var id=GameEvents.Subscribe(event,fn);subscriptions.push(id);return id;},Cancel:function(){generation++;timers.forEach(function(t){if($.CancelScheduled)$.CancelScheduled(t);});timers=[];},Dispose:function(){this.Cancel();subscriptions.forEach(function(id){if(GameEvents.Unsubscribe)GameEvents.Unsubscribe(id);});subscriptions=[];},Pending:function(){return timers.length;}};};
    U.Fit=function(panel,root,width,height,options){options=options||{};var w=(root.actuallayoutwidth||1672)/(root.actualuiscale_x||1),h=(root.actuallayoutheight||941)/(root.actualuiscale_y||1),s=options.reference?Math.min(w/options.reference[0],h/options.reference[1]):Math.min(w*(options.widthFraction||.95)/width,h*(options.heightFraction||.9)/height);apply(panel,{transform:"scale3d("+s+","+s+",1)"});return s;};
    U.IconButton=function(parent,props){props=props||{};var b=create("Button",parent,props.id,"UIIconButton");b.hittestchildren=false;U.Icon(b,props.iconId,props.glyphSize||28);if(props.label!==undefined)label(b,props.label,"UIIconLabel");U.State.Set(b,props);U.State.Bind(b,props.action);return b;};
    U.ActionButton=function(parent,props){props=props||{};var b=create("Button",parent,props.id,"UIActionButton");b.AddClass(props.variant==="gold"?"UIGold":"UIIvory");if(props.iconId)U.Icon(b,props.iconId,24);label(b,props.label,"UIButtonLabel");b.hittestchildren=false;U.State.Set(b,props);U.State.Bind(b,props.action);return b;};
    U.ActionButton.Adopt=function(b,props){if(!valid(b))return b;props=props||{};b.AddClass("UIActionButton");b.AddClass(props.variant==="gold"?"UIGold":"UIIvory");apply(b,{backgroundColor:"transparent",border:"0px"});function textColor(p){if(typeof p.text==="string")apply(p,{color:U.Tokens.colors.text_on_light});for(var i=0;i<p.GetChildCount();i++)textColor(p.GetChild(i));}textColor(b);U.State.Set(b,props);if(props.action)U.State.Bind(b,props.action);return b;};
    U.CloseButton=function(button,action){if(!valid(button))return;button.AddClass("UICloseButton");apply(button,{backgroundImage:"none",backgroundColor:"transparent",border:"0px"});button.hittestchildren=false;for(var i=0;i<button.GetChildCount();i++)button.GetChild(i).visible=false;U.Icon(button,"icon.close",28);U.State.Bind(button,action);};
    U.NavToggle=function(parent,props){props=props||{};var b=create("RadioButton",parent,props.id,"UINavToggle");b.group=props.group||"UINav_"+(++serial);b.checked=!!props.selected;if(props.iconId)U.Icon(b,props.iconId,28);label(b,props.label,"UINavLabel");U.State.Set(b,props);U.State.Bind(b,props.action);return b;};
    U.NavToggle.Adopt=function(p,props){p.AddClass("UINavToggle");U.State.Set(p,props);return p;};
    U.TabBar=function(parent,props){var bar=create("Panel",parent,props.id,"UITabBar"),buttons={};(props.items||[]).forEach(function(item){var b=create("Button",bar,"","UITab");label(b,item.label,"UITabLabel");U.State.Set(b,{enabled:item.enabled!==false,selected:item.id===props.selectedId});U.State.Bind(b,function(){if(props.onChange)props.onChange(item.id);});buttons[item.id]=b;});return {panel:bar,Select:function(id){Object.keys(buttons).forEach(function(k){U.State.Set(buttons[k],{selected:k===id});});}};};
    U.TabBar.Adopt=function(button,selected){button.AddClass("UITab");U.State.Set(button,{selected:selected});return button;};
    function cardSkin(card,variant){card.AddClass(variant==="augment"?"UICardAugment":variant==="product"?"UICardProduct":"UICardSquare");if(variant==="outline")card.AddClass("UIOutlineCard");}
    U.CardShell=function(parent,props){props=props||{};var card=create("Panel",parent,props.id,"UICard");cardSkin(card,props.bodyVariant);if(props.artId)U.Image(card,props.artId,"UICardArt");if(props.title!==undefined)label(card,props.title,"UICardTitle");U.State.Set(card,props);return card;};
    U.CardShell.Adopt=function(card,props){props=props||{};card.AddClass("UICard");cardSkin(card,props.bodyVariant);U.State.Set(card,props);return card;};
    U.ProgressBadge=function(parent,props){var l=label(parent,"","UIProgressBadge");l.visible=props.visible!==false&&props.current!==undefined&&props.required!==undefined&&Number(props.required)>0;if(l.visible)l.text=String(props.current)+"/"+String(props.required);return l;};
    U.ArchiveCard=function(parent,props){var card=U.CardShell(parent,{artId:props.artId,title:props.name});U.ProgressBadge(card,props);if(props.unlocked!==undefined)label(card,props.unlocked?"已解锁":"未解锁","UIUnlockLabel");if(props.tooltipData)U.Tooltip.Bind(card,props.tooltipData);return card;};
    U.PriceLabel=function(parent,props){var p=create("Panel",parent,"","UIPriceLabel");(props.prices||[]).forEach(function(price){var row=create("Panel",p,"","UIPriceRow"),currency=String(price.currencyName||price.currency||""),isU=currency==="U币"||currency.toLowerCase()==="ucoin";label(row,String(price.amount)+(isU?"":" "+currency),"UIPrice");if(isU){var host=create("Panel",row,"","UIPriceCurrencyIcon");apply(host,{width:"22px",height:"22px",overflow:"clip"});var coin=U.Image(host,"project.custom_game.main_hud_v1.currency_icon_64","UIPriceCoinImage");apply(coin,{width:"83px",height:"83px",position:"-30px -30px 0px"});}});if(props.paymentMode)label(p,props.paymentMode,"UIPriceMode");(props.originalPrices||[]).forEach(function(price){label(p,String(price.amount)+" "+String(price.currencyName||price.currency||""),"UIOriginalPrice");});return p;};
    U.ProductCard=function(parent,props){var card=U.CardShell(parent,{bodyVariant:"product",artId:props.artId,title:props.name});if(props.kind)label(card,props.kind,"UICaption");if(props.duration)label(card,props.duration,"UICaption");U.PriceLabel(card,{prices:props.prices,originalPrices:props.oldPrices,paymentMode:props.paymentMode});if(props.purchaseState)card.purchase=U.ActionButton(card,{label:props.purchaseState.label||"购买",enabled:props.purchaseState.enabled,busy:props.purchaseState.busy,action:props.action});return card;};
    U.BundleCard=function(parent,props){var c=U.ProductCard(parent,props);(props.items||[]).forEach(function(item){var slot=create("Panel",c,"","UIBundleItem");if(item.artId)U.Image(slot,item.artId,"UIBundleArt");label(slot,item.name||"","UICaption");if(item.quantity!==undefined)label(slot,String(item.quantity),"UICaption");});return c;};
    U.VipBundleCard=function(parent,props){var next={};Object.keys(props).forEach(function(k){next[k]=props[k];});next.purchaseState={label:props.eligible?"购买":"条件未达成",enabled:props.eligible===true,busy:props.purchaseState&&props.purchaseState.busy};var c=U.BundleCard(parent,next);if(props.requiredVipLevel!==undefined)label(c,"需要 VIP "+props.requiredVipLevel,"UICaption");return c;};
    U.ProgressBar=function(parent,props){var track=create("Panel",parent,"","UIProgressBar"),fill=create("Panel",track,"","UIProgressFill");track.visible=Number(props.max)>0;apply(fill,{width:(track.visible?Math.max(0,Math.min(100,Number(props.current)/Number(props.max)*100)):0)+"%"});if(props.label!==undefined)label(track,props.label,"UIProgressLabel");return track;};
    U.Checkbox=function(parent,props){var b=create("ToggleButton",parent,props.id);b.checked=!!props.checked;U.Checkbox.Adopt(b);label(b,props.label,"UICheckboxLabel");U.State.Set(b,props);U.State.Bind(b,function(){if(props.onChange)props.onChange(!!b.checked);});return b;};
    U.Checkbox.Adopt=function(b){if(!valid(b)||b.BHasClass("UICheckbox"))return b;b.AddClass("UICheckbox");U.Icon(b,"checkbox.off",24,"UICheckOff");U.Icon(b,"checkbox.on.normal",24,"UICheckOn");return b;};
    U.Tooltip={Bind:function(p,data){p.SetPanelEvent("onmouseover",function(){var d=typeof data==="function"?data():data;$.DispatchEvent("DOTAShowTextTooltip",p,String(d.title||"")+"\n"+String(d.body||""));});p.SetPanelEvent("onmouseout",function(){$.DispatchEvent("DOTAHideTextTooltip");});},Adopt:function(panel){if(valid(panel))panel.AddClass("UITooltip");return panel;}};
    U.FilterBar=function(parent,props){var bar=create("Panel",parent,"","UIFilterBar");if(props.search!==undefined){var entry=create("TextEntry",bar,"","UISearch");entry.text=props.search||"";entry.SetPanelEvent("ontextentrychange",function(){if(props.onSearch)props.onSearch(entry.text);});}(props.filters||[]).forEach(function(f){U.Checkbox(bar,{label:f.label,checked:f.checked,enabled:f.enabled,onChange:function(v){if(props.onChange)props.onChange(f.id,v);}});});return bar;};
    U.RewardGrid=function(parent,props){var grid=create("Panel",parent,"","UIRewardGrid");(props.items||[]).forEach(function(item){var card=U.CardShell(grid,{artId:item.artId,title:item.name,selected:item.id===props.selectedId});if(props.renderArt)props.renderArt(card,item);U.State.Bind(card,function(){if(props.onInspect)props.onInspect(item);});});return grid;};
    U.ModalManager={Top:function(){return cfg.SurvivalUILayers?cfg.SurvivalUILayers.Top():null;},CloseTop:function(){if(cfg.SurvivalUILayers)cfg.SurvivalUILayers.CloseTop();},Register:function(id,entry){if(modals[id]&&modals[id]!==entry)modals[id].Dispose();modals[id]=entry;},Get:function(id){return modals[id];}};
    U.ModalShell={Adopt:function(props){var panel=props.panel,life=U.Lifecycle(),open=false;panel.AddClass("UIModal");apply(panel,{backgroundImage:"none",backgroundColor:U.Tokens.colors.surface_ivory,border:"1px solid "+U.Tokens.colors.border_champagne,boxShadow:"#00000050 0px 5px 18px 0px",width:props.width+"px",height:props.height+"px",horizontalAlign:"center",verticalAlign:"center",position:"0px 0px 0px",margin:"0px"});
        var header=props.header;if(valid(header)){header.AddClass("UIModalHeader");apply(header,{backgroundImage:"none",backgroundColor:U.Tokens.colors.surface_teal});}if(valid(props.titlePanel)){props.titlePanel.AddClass("UIFontTitle");apply(props.titlePanel,{color:U.Tokens.colors.text_on_dark});}
        var scrim=props.scrim||create("Button",panel.GetParent(),"","UIModalScrim");scrim.AddClass("UIModalScrim");apply(scrim,{backgroundImage:"none",backgroundColor:"#0000008c"});
        function requestClose(){if(U.ModalManager.Top()!==props.id||props.closePolicy==="mandatory")return;if(props.onClose)props.onClose();else api.Close();}
        var click=props.scrimButton||scrim;
        if(!props.scrimButton&&panel.GetParent()===scrim){click=create("Button",scrim,"","UIModalHitArea");apply(click,{width:"100%",height:"100%",zIndex:"0",backgroundColor:"transparent"});}
        // The visible window is the input boundary, including transparent artwork
        // and empty header/footer/list space. Children keep their own interactions.
        function consume(){return true;}
        panel.hittest=true;panel.hittestchildren=true;
        panel.SetPanelEvent("onactivate",consume);
        var shield=create("Button",panel,"","UIModalInputShield");
        apply(shield,{width:"100%",height:"100%",position:"0px 0px 0px",horizontalAlign:"left",verticalAlign:"top",ignoreParentFlow:"true",zIndex:"-1000",backgroundColor:"transparent",backgroundImage:"none",border:"0px",margin:"0px",padding:"0px"});
        shield.hittest=true;shield.hittestchildren=false;shield.tabindex=-1;
        shield.SetPanelEvent("onactivate",consume);
        if(shield.SetAcceptsFocus)shield.SetAcceptsFocus(false);
        function inputEnabled(enabled){
            panel.hittest=enabled;panel.hittestchildren=enabled;
            scrim.hittest=enabled&&click===scrim;scrim.hittestchildren=enabled&&click!==scrim;
            click.hittest=enabled;click.hittestchildren=false;
        }
        click.SetPanelEvent("onactivate",function(){if(open&&props.closePolicy!=="explicit")requestClose();return true;});
        U.CloseButton(props.closeButton,requestClose);
        function fit(){if(!open)return;if(!valid(panel)){open=false;life.Cancel();return;}if(props.width&&props.height)U.Fit(panel,props.root||$.GetContextPanel(),props.width,props.height,props.fit);life.Later(.25,fit);}
        var api={panel:panel,frameId:"frame.window",frameStatus:"pending_clean_asset_programmatic_fallback",Open:function(){if(!valid(panel))return;if(!open){life.Cancel();open=true;fit();}inputEnabled(true);panel.visible=true;scrim.visible=true;panel.RemoveClass("UIClosed");if(cfg.SurvivalUILayers)cfg.SurvivalUILayers.Open(props.id,panel,requestClose,{scrim:scrim,click:click});else{apply(panel,{zIndex:"100000"});apply(scrim,{zIndex:"99999"});}},Close:function(){open=false;life.Cancel();if(valid(panel)){panel.hittest=false;panel.hittestchildren=false;panel.visible=false;panel.AddClass("UIClosed");}if(valid(scrim)){scrim.hittest=false;scrim.hittestchildren=false;scrim.visible=false;}if(valid(click))click.hittest=false;if(cfg.SurvivalUILayers)cfg.SurvivalUILayers.Close(props.id);},RequestClose:requestClose,Dispose:function(){api.Close();life.Dispose();},IsOpen:function(){return open;}};U.ModalManager.Register(props.id,api);return api;
    }};
    U.FullscreenShell={Adopt:function(props){var panel=props.panel;panel.AddClass("UIFullscreen");if(props.sceneId){apply(panel,{backgroundImage:"none",backgroundColor:"transparent"});var scene=create("Panel",panel,"","UISceneLayer");scene.hittest=false;scene.hittestchildren=false;apply(scene,{backgroundImage:'url("'+U.Asset(props.sceneId)+'")',backgroundSize:"cover",backgroundPosition:"center",width:"100%",height:"100%",zIndex:"-2"});if(props.themeArtId)U.Image(panel,props.themeArtId,"UIThemeArtLayer");var gradient=create("Panel",panel,"","UIReadingGradient");gradient.hittest=false;gradient.hittestchildren=false;}else if(props.liveGame)apply(panel,{backgroundColor:"#0000008c"});return panel;}};
    U.HUDShell={Adopt:function(panel){panel.AddClass("UIHUDShell");return panel;}};
    U.DrawResultSequence=function(){var life=U.Lifecycle();return {Cancel:function(){life.Cancel();},Play:function(results,props){life.Cancel();var list=(results||[]).slice();if(!list.length)return;var timing=props.timing;function later(ms,fn){life.Later(ms/1000,fn);}later(650,props.onCharged);list.forEach(function(item,i){later(timing.enter+(timing.enterStep||0)*i,function(){props.onEnter(i,item);});var at=timing.flip+(timing.flipStep||0)*i;later(at,function(){props.onFlip(i,item);});later(at+props.flipHalf,function(){props.onReveal(i,item);});});later(timing.ready,props.onReady);},Dispose:function(){life.Dispose();}};};
    U.AugmentChoiceGroup=function(){var life=U.Lifecycle();return {Later:life.Later,Cancel:life.Cancel,Dispose:life.Dispose,Animate:function(card,index){life.Later(.01+index*.11,function(){card.slot.style.opacity="1";card.slot.style.transform="translate3d(0px,-8px,0px) scale3d(1,1,1)";});life.Later(.56+index*.11,function(){card.slot.AddClass("RogueSettle");card.slot.style.transform="translate3d(0px,0px,0px) scale3d(1,1,1)";});life.Later(.75+index*.11,function(){card.flip.style.transform="rotateY(90deg)";});life.Later(1.02+index*.11,function(){card.front.visible=true;card.back.visible=false;card.flip.AddClass("RogueInstant");card.flip.style.transform="rotateY(-90deg)";life.Later(.01,function(){card.flip.RemoveClass("RogueInstant");card.flip.style.transform="rotateY(0deg)";});});}};};
    cfg.SurvivalUI=U;
})();
